version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "/fc43-action"
      - "/fc44-action"
    schedule:
      interval: "weekly"
