version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/fc41-action"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/fc42-action"
    schedule:
      interval: "daily"
