name: Comment on pull request

on:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  contents: read

jobs:
  comment-on-pull-request:
    name: Comment on PR to set expectations
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # to allow the workflow to comment on the PR
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for opening a pull request!  I try to review this repo at least once a week.'
            })
